-- Executable Vault-authenticated definition: fix_phase3_scheduler.sql.
-- Review NOTIFICATIONS.md; install only after Phase 3 staging verification.
-- This compatibility pointer intentionally installs nothing.
