"""Assemble release evidence only; never read .env or secret.txt."""
import json, hashlib
from pathlib import Path
from datetime import datetime, timezone, timedelta
root=Path(__file__).resolve().parent.parent
if (root/'scripts/phase4-postfix-release-baseline.json').exists():
    raise SystemExit('Historical pre-fix generator retired. Use node scripts/write-phase4-postfix-report.mjs after current final regressions.')
def read_json(name): return json.loads((root/name).read_text(encoding='utf-8-sig'))
reg=read_json('scripts/phase4-final-regression-results.json')
assert len(reg['results'])==10 and all(x['exitCode']==0 for x in reg['results']), 'Final regression run incomplete or failed'
db=read_json('scripts/phase4-database-inventory.json')
browser=read_json('scripts/phase4-browser-results.json')
p4=read_json('scripts/phase4-verification-results.json')
excel=read_json('scripts/phase4-spreadsheet-results.json')
report_counts=read_json('scripts/phase4-report-count-results.json')
assert report_counts['result']=='PASS'
audit=read_json('scripts/phase4-dependency-audit.json')
baseline=read_json('scripts/phase4-release-baseline.json')
changed=[name for name,h in baseline.items() if hashlib.sha256((root/name).read_bytes()).hexdigest()!=h]
assert not changed, 'Frozen release files changed'
stamp=datetime.now(timezone(timedelta(hours=8))).isoformat(timespec='seconds')
def table(head,rows):
    return '| '+' | '.join(head)+' |\n|'+ '|'.join(['---']*len(head))+'|\n'+ '\n'.join('| '+' | '.join(str(v).replace('|','\\|').replace('\n',' ') for v in row)+' |' for row in rows)+'\n'
out=[]
def section(title,text): out.append('## '+title+'\n\n'+text.strip()+'\n')
out.append(f'''# MedicAppointment — Final Verification and Release Readiness Report

**Timestamp:** {stamp}, Asia/Manila (UTC+08:00).

**Workspace:** D:\\Development\\Projects\\draft. **Release candidate:** current Phase 1–3 workspace, not merely Git HEAD; existing changes are uncommitted/untracked relative to the older repository baseline.

**Audit Scope**

Read the original audit and Phase 1, 2 and 3 reports first. On resume, PHASE4_CONTINUATION.md was absent; saved test outputs, the release checklist and 78-file SHA256 baseline supplied the recoverable state. The continuation file was then created. The final report was also absent. No existing Phase 1–3 changes were reverted. Completed checks were reused, followed by the explicitly requested complete final regression run.

No production deployment, hosted database reset, real patient query/deletion, hosted demonstration seeding or external SMS send occurred. Tests created disposable loopback PostgreSQL databases and synthetic records only. Actual browser requests to non-loopback endpoints were intercepted; remote WebSockets were replaced with an offline loopback endpoint. Existing .env values were not printed. secret.txt was privately classified without displaying values. A nondefault Git whitespace diagnostic emitted source context; subsequent checks captured and sanitized Git output rather than reproducing source lines. No application or database-source feature changes were made in Phase 4.

**Evidence classifications:** CONFIRMED means demonstrated at the stated local/mocked boundary; PARTIAL means implemented/tested with an explicit remaining limitation; NOT VERIFIED means the integration/environment was not exercised. Traceability uses FIXED, ACCEPTED LIMITATION, NOT VERIFIED and STILL BROKEN. None of these labels equates local SQL/mocked Auth with a configured hosted Supabase installation.

**Freeze evidence:** all {len(baseline)} files in scripts/phase4-release-baseline.json still match. Original audit and Phase 1–3 reports were preserved. The only pre-existing verification file corrected was scripts/test-phase2-ui.mjs: fixed sleeps became bounded request-condition waits, with all assertions retained. Added Phase 4 scripts/artifacts/checklist/continuation/report provide verification only.
''')
section('A. Executive Summary','''The release candidate passes clean installation of dependencies, TypeScript/Vite build, static verification, all Phase 1–3 regressions, offline Edge type checking, additional Phase 4 database checks, Chrome/Edge synthetic browser checks and normal Excel CSV opening. The critical role-escalation and unrestricted appointment-write defects are closed in the tested local schema. Privacy-safe availability, schedule validity, exact-slot concurrency and Manila time handling remain protected.

This is **not a production approval**. No real Supabase Auth/PostgREST/browser chain, hosted migration, live scheduler, live Realtime, provider delivery or production role audit has been verified. The final npm dependency audit still exits 1 with three moderate and one high vulnerable package classifications. A tracked file contains anon-role JWT material; no service-role JWT/password was identified by the categorical scan, but current validity, repository history and deployed default accounts remain unverified.

| Target | Classification | Reason |
|---|---|---|
| School demonstration | **NOT READY for a complete connected demonstration** | Local synthetic demonstrations and code/test walkthroughs work. A real isolated Auth/database rehearsal and configured demonstration environment are still missing; mocked HTTP must not be presented as hosted functionality. |
| Staging deployment | **READY WITH PREREQUISITES** | Reviewed incremental files are locally executable; staging ownership/extensions/Auth/schema cache/secrets, backups and synthetic E2E must be configured and tested. |
| Real production | **NOT READY** | All staging integration/operational evidence, security hygiene, dependency review, role review, recovery and notification procedures remain prerequisites. |

No new application release-blocking defect was confirmed during Phase 4. Initial additional-test failures were fixture/adapter/selector expectations; they were corrected without weakening application safeguards. Existing limitations and verification gaps are explicitly listed below.''')
section('B. Release Candidate Architecture','''React 18.3, React Router 6 declarative BrowserRouter/Routes, TypeScript and Vite form the SPA. Installed lockfile versions include Vite 5.4.21, esbuild 0.21.5, react-router/react-router-dom 6.30.6 and @supabase/supabase-js 2.116.0. package-lock.json version 3 agrees with package.json root dependencies and devDependencies.

src/App.tsx mounts independent patient and staff providers. src/lib/supabaseClient.ts creates clients with persistent/auto-refreshing sessions, URL detection disabled, storage keys medical-patient and medical-appointments-staff. usePortalAuth/portalIdentity/asyncState resolve one identity packet atomically, reject wrong roles, clear stale patient/profile state, apply initialization/query deadlines and unsubscribe. signOut uses local scope.

Ten public application tables, RLS, column ACLs, SECURITY DEFINER functions with explicit safe search_path and EXECUTE ACLs implement the backend. Appointment browser writes are SELECT-only plus approved ownership/admin RPCs. All patient/staff availability and writes share _clinic_schedule_slots/_assert_slot_bookable. PostgreSQL timestamptz stores instants; clinicTime.ts supplies Manila dates/times/ranges/weeks.

Appointment mutation invalidation refreshes local mounted views. The staff auth provider owns one debounced appointment Realtime subscription; patients have no global feed. Optional publication installation is separate.

Phase 3 SQL creates an appointment-versioned SMS outbox/ledger. send-confirmation verifies Auth and SQL ownership; send-reminders uses CRON_SECRET; notification-status verifies a Twilio signature. Worker claims/leases and result persistence distinguish provider acceptance from later delivery. Vault-backed five-minute scheduler installation is separate. Reports use admin-only complete SQL aggregation and paged audit RPCs, with shared spreadsheet-safe CSV encoding.

Required migrations, Edge folders/configuration, scheduler/publication files, environment example and verification scripts exist. .env.example has only fake placeholders for the three public frontend variables and server-only variable names in comments.''')
out.append('''### Phase 4 verification files

Changed existing verification file: scripts/test-phase2-ui.mjs (bounded waits only). New files: MEDICAPPOINTMENT_RELEASE_CHECKLIST.md, PHASE4_CONTINUATION.md, MEDICAPPOINTMENT_FINAL_VERIFICATION_REPORT.md; scripts/test-phase4.mjs, test-phase4-browser.mjs, test-phase4-reports.mjs, verify-release.mjs, write-final-report.py; scripts/phase4-release-baseline.json, phase4-dev-server-port.txt, phase4-database-inventory.json, phase4-verification-results.json, phase4-browser-results.json, phase4-final-regression-results.json, phase4-report-count-results.json, phase4-dependency-audit.json, phase4-synthetic-export.csv, phase4-spreadsheet-results.json, phase4-chrome-mobile.png and phase4-edge-mobile.png. These filenames under scripts are verification artifacts, not application modules. Installed node_modules/build dist are generated outputs from the required npm commands. No Phase 4 migration, application feature change or package-lock modification was introduced.
''')
section('C. Phase 1–3 Regression Results',table(['Command','Exit','Seconds','Result'],[(r['command'],r['exitCode'],r['seconds'],'PASS') for r in reg['results']])+'''
Counts: static verify 69; Phase 1 25; Phase 2 9 mounted/timezone + 14 database; Phase 3 19 mounted/provider/component + 15 database, plus canonical equality; Edge 7 TypeScript files offline; Phase 4 12 additional SQL/handler/CSV checks; browser 20 checks across Chrome and Edge. Final exact outputs are preserved below and in scripts/phase4-final-regression-results.json.

Additional independent report oracle: node scripts/test-phase4-reports.mjs exited 0 after the required regression run. Exact result: PASS Phase 4 report oracle: 1211 total / 4 no-shows / 1201 cancelled / 3 walk-ins; eight statuses, ID isolation, clinic midnight, doctor/empty filters and audit 100+85 under three SQL timezones. Evidence scripts/phase4-report-count-results.json. No application changes preceded/followed that extra verification.

Build: tsc --noEmit && vite build, 118 modules, dist/index.html 1.18 kB; CSS index-CvtWwqyU.css 40.13 kB (gzip 7.52 kB); JS index-BeQGGMKx.js 521.43 kB (gzip 144.31 kB). The >500 kB chunk warning remains LOW/nonblocking. No compiler error remains. No ESLint script/configuration is configured; no lint success is claimed.

Clean npm ci: 149 packages added, 150 audited; successful exit 0, with four dependency vulnerability classifications. Two initial attempts failed EPERM unlink on workspace node_modules/@esbuild/win32-x64/esbuild.exe and @rollup/rollup-win32-x64-msvc/rollup.win32-x64-msvc.node, errno -4048. They were locked by a verified workspace Vite process; that process was stopped and its port 5173 recorded for restoration. No package/lock changes were made. A final clean npm ci passed again.

The first parallel Phase 2 run failed scripts/test-phase2-ui.mjs:80 with TypeError: Cannot read properties of undefined (reading 'request'). The fixture waited eight milliseconds rather than waiting for the deferred request to exist. Three-second bounded predicate waits now observe requests before resolving them; all prior assertions pass. New Phase 4 fixtures initially expected date-block conflicts to throw rather than return success:false/conflict_count, parsed raw UUID output as JSON, and conflated accepted status with delivery_status. Browser fixture issues included mocked preflight headers, unpadded 9:00, sidebar selectors and cancelled CDP interceptions. None required an application change.

Default git diff --check exits 0. Nondefault core.autocrlf=false treated existing CRLF as trailing whitespace and produced source context; those diagnostics were not used to rewrite frozen files. Default Git LF/CRLF notices are informational.
''')
out.append('### Exact final regression command outputs\n')
for r in reg['results']:
    output=(r.get('stdout','')+r.get('stderr','')).strip() if 'stdout' in r else json.dumps(r,indent=2)
    out.append('**'+r['command']+' — exit '+str(r['exitCode'])+'**\n\n```text\n'+output+'\n```\n')
section('D. Fresh Install Verification','''**CONFIRMED locally:** the entire intended non-demo supabase/schema.sql executes in an empty disposable PostgreSQL 18 cluster. The harness creates synthetic auth.users/auth.uid() and Supabase-like roles; this is SQL compatibility testing, not a complete Supabase Auth/REST stack. No demo section/seeder was executed. Phase 1–3 canonical definitions are checked against schema.sql/full.sql/legacy sources by existing regressions.

Fresh inventory: all ten tables have RLS enabled. Primary/foreign keys, schedule checks/exclusion, whole-minute appointments, exact-slot index, triggers and required RPCs are present. The evidence artifact scripts/phase4-database-inventory.json contains every table, index, constraint definition, policy, trigger and the 21 explicitly checked public RPC signatures/configurations/EXECUTE privileges.

''' + table(['Table','RLS','Purpose'],[(t,'Enabled','Clinical/core table' if t not in ['notification_attempts','appointment_notification_versions'] else 'Private notification state') for t in db['tables']])+
table(['Table','RLS policy','Command'],[(x['table'],x['name'],x['command']) for x in db['policies']])+
table(['Index'],[(x,) for x in db['indexes']])+
table(['Table','Constraint','Definition'],[(x['table'],x['name'],x['definition']) for x in db['constraints']])+
table(['Trigger'],[(x,) for x in db['triggers']])+
table(['RPC signature','SECURITY DEFINER','Settings','Anon execute','Authenticated execute','Service execute'],[(x['signature'],x['securityDefiner'],x['settings'],x['anonymousExecute'],x['authenticatedExecute'],x['serviceExecute']) for x in db['rpcs']])+'''
**NOT VERIFIED:** Supabase platform migration ownership, auth.users permissions, extension versions/default grants, PostgREST schema cache, first real admin bootstrap and actual hosted catalog drift. Existing databases must use incremental migrations, not this fresh schema.''')
section('E. Migration Verification','''**CONFIRMED locally:** scripts/test-phase4.mjs loads the original Git HEAD schema into a separate synthetic pre-upgrade database, inserts valid profiles/patients/doctors/schedules/appointments/notes/audit/unavailable-date rows, then applies Phase 1 → Phase 2 → Phase 3. After every migration, ordered JSON snapshots of all eight clinical tables are exactly unchanged; roles/UUIDs/history/notes/audit and uq_doctor_slot OID remain intact. Repeating the chain also preserves rows. Existing Phase 1–3 suites test individual repeatability and fresh/legacy installation variants.

Incompatible zero-duration and overlapping pre-upgrade schedules fail Phase 2 without deleting/rewriting rows. A blank-name doctor fails Phase 3 similarly. Phase 2 regressions also reject old non-minute appointments unchanged; Phase 1 tests verify exact index definition/authorization boundary. A preflight failure requires private authorized reconciliation, not deletion, rounding or reset.

**NOT VERIFIED:** a copy of the actual hosted schema/data; current real constraint/grant drift; existing legacy blocks/appointments, invalid demographics, overlapping duration histories and suspicious admin assignments. No production fixture was copied. Modern and legacy upgrade paths must be chosen after catalog review, not guessed.''')
section('F. Authentication Verification','''**CONFIRMED at local boundaries:** mounted real hooks reject stale identity results, clear previous patient state immediately, finish missing/failed linkage with explicit errors, fail wrong roles closed, clean listeners and use local signout. SQL ensure_patient_identity provisions patient-only records for an exact Auth UUID and never matches names; concurrent provisioning creates one link. admin_link_patient refuses an identity already attached elsewhere.

Actual built React/Supabase SDK in Chrome and Edge exercised synthetic password rejection, signup, identity provisioning response, reload/session restoration, query/identity error recovery, two storage keys, wrong-role restored sessions, logout/login and local signout isolation. Both unrelated portal keys coexist; staff signout leaves the patient key; patient signout removes its own key.

No hosted account or personal browser profile was used. Auth/token/REST responses were intercepted fixtures. **NOT VERIFIED:** real signup/email confirmation, Auth password policy/email delivery, real refresh/revocation/expired-session behavior, multi-device/global logout, actual gateway JWT verification and reset/password-change delivery. Missing patient SQL provisioning is tested; a genuine hosted missing-record failure remains unverified. Password reset is deliberately clinic-assisted, not an email workflow.''')
section('G. RLS / Authorization Verification','''All important denial decisions below were exercised under PostgreSQL roles/auth.uid(), not inferred from hidden React controls. Patient A/B are separate synthetic UUIDs. Admin authorized clinic operations remain functional.

''' + table(['Actor/action','Local result','Evidence'],[
('Anonymous protected profile/patient/appointment/ledger reads','Denied or no rows','Phase 4 anonymous assertions'),('Anonymous table mutation, booking/private/admin RPC','Denied','Phase 1/4 EXECUTE/table ACL'),('Patient A own profile/patient/appointments','Allowed','Phase 1/4 RLS reads'),('Patient A Patient B private rows/update','No rows/no mutation','Phase 4 RLS assertions'),('Patient A own eligible book/reschedule/cancel','Allowed','Phase 1/4 RPC lifecycle'),('Patient A Patient B move/cancel','Denied','Owner RPC assertions'),('Patient A direct clinical/completed/check-in writes','Denied','No appointment mutation grant'),('Patient A staff booking/admin role RPC','Denied','Explicit backend role checks'),('Patient A report/worker RPC/other notification ledger','Denied/zero rows','Phase 3/4 grants/RLS'),('Admin booking/calendar/status/report/demographics','Allowed when valid','Phase 1–4 actual SQL'),('Admin self-demotion and invalid role','Denied','admin_set_profile_role regression')])+'''
Role-escalation attempts: direct UPDATE own role; INSERT explicit admin role; ON CONFLICT UPSERT role; admin_set_profile_role as patient; malformed UUID; extra ensure_patient_identity arguments; forged user_metadata/app_metadata role claim. All fail or are ignored, while profile device_label/permitted fields still update. Changing a frontend payload cannot add a granted role column or bypass SQL authorization. The HTTP browser facade is synthetic: **actual REST/table mutation at deployed PostgREST is NOT VERIFIED**, although its underlying SQL ACLs are tested.

profiles permits only granted safe profile columns; administrative role changes require the protected RPC/trusted backend. appointments permits browser SELECT, no direct INSERT/UPDATE/DELETE for either portal. patients ownership plus column-limited updates protect Auth linkage. Doctors/schedules/blocked dates/notes are admin writes with validation; reports admin-only; ledger is admin read and service worker only. SECURITY DEFINER safe search_path and explicit ACLs are regression-tested, including temporary-table spoofing.

Database owners/service_role remain trusted and may bypass browser rules. Unknown deployed functions, role memberships, superuser/owner rights and previously escalated admins require staging/private review. No claim that local RLS repairs an unapplied hosted database.''')
section('H. Patient E2E',table(['Step/case','Evidence boundary','Result'],[
('Register → profile/patient provisioning','Chrome/Edge actual bundle with intercepted Auth/RPC; separate real SQL provisioning','CONFIRMED locally; hosted NOT VERIFIED'),('Login / wrong password','Real SDK/forms, synthetic Auth responses','CONFIRMED locally'),('Dashboard / profile / settings / history / appointments direct refresh','Chrome/Edge route loads/session storage','CONFIRMED locally'),('Profile permitted edit/name mirroring','Actual patient_save_profile SQL and mounted form validation','CONFIRMED locally; complete browser edit NOT VERIFIED'),('Doctor → date → time → review → book → success/list','Chrome/Edge real UI with safe fixture slots','CONFIRMED mocked transport'),('Confirmation accepted/failure/stub wording','Real notification helper tests + SQL/handler/provider integration','CONFIRMED mocks; real SMS NOT VERIFIED'),('Reschedule → new time appears → cancel → history','Chrome/Edge controls + separate actual RPC SQL','CONFIRMED local boundaries'),('Logout → login again → restoration','Chrome/Edge actual SDK/local storage','CONFIRMED synthetic Auth'),('Query failure → Retry; identity failure → Retry account loading','Chrome/Edge + deadlines in mounted tests','CONFIRMED synthetic errors'),('Wrong portal role / stale previous identity','Browser restored-role fixture + real hook generation race','CONFIRMED locally'),('Missing patient and duplicate provisioning','Actual ensure_patient_identity SQL/concurrency','CONFIRMED locally'),('Expired real JWT/network transport/email confirmation','No real Auth/gateway','NOT VERIFIED'),('Different browser timezone','Manila/UTC/New York actual rendered appointment string','CONFIRMED mocked backend')])+'''
The UI and database layers were tested separately. A complete connected registration-to-logout flow through real Supabase Auth/PostgREST/functions is **NOT VERIFIED**; the fixture harness is not a substitute demonstration backend.''')
section('I. Staff E2E',table(['Step/case','Evidence','Result'],[
('Login/dashboard/all protected pages direct refresh','Chrome/Edge actual bundle/SDK with synthetic admin','CONFIRMED mocked transport'),('Patient search/create/edit','Actual RLS/validation SQL; source/mounted pending/query tests','PARTIAL; full browser mutation sequence NOT VERIFIED'),('Intentional Auth link and conflicts','Mounted actual link form + Phase 2/3 backend RPC','CONFIRMED locally; real identity proof NOT VERIFIED'),('Doctor create/edit/activate/deactivate','Actual admin SQL validation/history preservation + form/source checks','CONFIRMED locally; complete browser sequence NOT VERIFIED'),('Schedule create/duplicate/overlap/invalid duration','Actual constraints/exclusion + form validation','CONFIRMED locally'),('Block date/conflict count/no silent cancellation','Actual SQL RPC/trigger + booking/block race','CONFIRMED locally'),('Booking/rescheduling/cancellation/list refresh','Actual SQL, mounted real Booking handlers/list renders','CONFIRMED locally; hosted browser NOT VERIFIED'),('Check-in → waiting → in_progress → completed','Actual SQL state machine/timestamp/date','CONFIRMED locally'),('No-show and pending confirmation where permitted','Phase 1 state/slot reuse regression','CONFIRMED locally'),('Terminal/skipped/future-day invalid transitions','Phase 1/4 rejected SQL','CONFIRMED locally'),('Reports/CSV','Actual aggregate fixtures, report page route, real encoder + Excel','CONFIRMED locally; full live export click NOT VERIFIED'),('Display-name/password/settings/roles','Mounted validation/source and backend profile/role ACL','PARTIAL; real Auth password change NOT VERIFIED'),('Logout independent patient session','Chrome/Edge SDK/local scope','CONFIRMED synthetic Auth')])+'''
No full staff workflow against a genuine Supabase service was exercised. Doctor/patient/calendar mutation browser sequences remain a required staging rehearsal, not assumed functional because controls exist.''')
section('J. Booking / Availability / Concurrency','''**CONFIRMED locally:** uq_doctor_slot is UNIQUE (doctor_id, scheduled_time), partial WHERE status NOT IN ('cancelled','no_show'). It is unchanged and its OID preserved across upgrades. Exactly one request wins each controlled race: Patient A vs B; patient vs staff; staff vs staff; reschedule vs booking; reschedule vs reschedule. A failed move retains its original appointment through transactional rollback.

09:00:00 on the schedule grid books; 09:00:01, 09:00:00.500 and off-grid 09:01 are rejected. Patient and staff writes call the same validator; direct browser writes are denied. Cancelled/no_show release exact slots; completed remains occupied. Availability returns only scheduled_time and slot_duration_minutes, not another patient's ID/name/reason/appointment row.

Scenario evidence: Phase 2/4 compare identical arrays for empty, partial, full, cancelled/no-show/completed, unavailable and inactive cases; current-day past slots are excluded; future weekday schedules apply; duplicate/overlapping/invalid duration rows fail; booking vs blocking serialization prevents conflicting commits. Blocking an occupied doctor date returns success:false/conflict_count and inserts no block. Existing valid/history rows stay preserved.

**ACCEPTED LIMITATION:** uniqueness protects exact starts, not overlapping intervals across a changed schedule grid and old visits at different starts. Schedule changes do not rewrite old visits; safe migration/history policy requires operator review of such cases. A stronger interval-history invariant was not silently introduced in verification. Previously existing blocked-date conflicts are preserved and need private reconciliation. Actual hosted occupancy/index/locks remain NOT VERIFIED.''')
section('K. Timezone Verification','''**CONFIRMED locally:** clinicTime.ts fixes Asia/Manila for clinicInstant, clinicDateKey/TimeKey, day/month half-open ranges, exact week dates and all format helpers. TypeScript strings map to PostgreSQL timestamptz instants; schedule TIME and blocked DATE retain clinic-calendar meanings. 2030-10-10 09:00 Manila equals 2030-10-10T01:00:00Z.

Phase 2 spawns Node under Asia/Manila/UTC/America/New_York and compares date/time/display/day/month/week results. PostgreSQL session timezones return equal slot epochs. Phase 3 verifies report UTC/Manila midnight and reminder morning/tomorrow boundaries. Chrome/Edge Emulation.setTimezoneOverride yields identical actual appointment list strings across all three zones.

Booking/rescheduling/backend check-in/report/reminder date logic and blocked/exact-week displays use shared clinic rules and local regressions. **NOT VERIFIED:** each complete real-provider/hosted/browser report/dashboard/history/blocked-week workflow under all three zones. Long-open dashboard day/week rollover has no dedicated clock subscription; refresh/reopen at clinic midnight is an accepted LOW limitation. Reminder fixtures inject a clock; no scheduler waited for real time.''')
section('L. Notifications / Reminder Verification','''**CONFIRMED locally:** committed approved appointment operations enqueue one versioned confirmation/reschedule/cancellation event through phase3_enqueue_notification; transaction failure enqueues nothing. Queue/claim/finish/result functions are service-only; ownership request RPC is owning patient/admin. Actual _shared/handlers.ts connects to the real local ledger through a JSON RPC adapter and a mocked Twilio transport. Repeat confirmation sends once. Accepted status is separate from delivery_status; callback SQL records delivered without changing provider acceptance.

Phase 3 handler tests cover OPTIONS/exact CORS, valid/invalid/null/missing/UUID JSON, unauthorized caller and patient/admin paths. Provider 400 is failed/rejected; 429 retry-aware failed; 500/network timeout unknown/held, not accepted. Booking stays committed for every failure. Mock tests exercise invalid destination, duplicate calls, SQL concurrent claim, bounded retries, lease expiry, stale supersession, reminder cancellation/reschedule and independent HMAC signature rejection. Logs/responses omit private destinations/message bodies/provider secrets.

Reminders select the next Manila clinic date after a 07:00 clinic-time gate; durable (appointment,type,revision,channel) uniqueness prevents duplicates. Cancelled/completed/no_show appointments are not newly reminded; reschedule supersedes the old revision and claims use the new instant. Ambiguous/expired/stubbed sends are held for operator reconciliation, not blindly replayed. Already-in-flight provider requests cannot be recalled.

Scheduler definition supabase/fix_phase3_scheduler.sql requires Phase 3, Vault/pg_cron/pg_net and three named Vault secrets. _invoke_notification_worker uses empty search_path, qualified net.http_post, cron-secret + anon headers, correct /functions/v1/send-reminders suffix, 10s queued HTTP timeout. Intended named job medicappointment-notification-worker runs */5 * * * *. Phase 3 tests install mocked Vault/net/cron and verify structure/idempotent name, not real extension execution.

**NOT VERIFIED:** installed Vault/cron/net, exactly one live job, actual project URL/auth, worker HTTP runtime, real Twilio acceptance/delivery, callback public URL/signature transport/early retries, quota/consent and backlog. Five-message batches per five-minute pass require staging capacity measurement; notifications are operationally PARTIAL, and automated hosted reminders are not claimed operational. No test destination was sent a real message.''')
section('M. Reports / CSV Verification','''**CONFIRMED locally:** staff_appointment_report groups by immutable patient/doctor IDs and Manila clinic dates, not names/runtime-local date slicing. Phase 3 fixtures manually assert total 1,505 for >REST-default-cap data, two same-name/different-ID doctors and patients, doctor filter and Manila 00:30 / previous UTC-date handling. staff_report_audit pages 105 rows as 100 then 5, with complete total. The independent Phase 4 oracle additionally asserts 1,211 visits across all eight statuses: 4 no-shows, 1,201 cancelled, 3 walk-ins, doctor totals 4/1,207, two same-name doctor IDs and two same-name flagged patient IDs (two no-shows each), empty aggregate and doctor filter. 23:59 preceding-day/00:00 next-day fixtures are excluded; 00:30 Manila is included despite previous UTC date. Audit fixtures total 185, paged 100 then 85 with distinct UUIDs. Every oracle result is identical under three SQL session timezones. Reports use one SQL aggregate rather than incomplete client downloads. Date range limit is 366 days; invalid/excessive input rejects explicitly. Patient/anonymous report access is denied.

csv.ts quotes every cell, doubles embedded quotes, emits UTF-8 BOM/CRLF records and prefixes dangerous string formulas (including leading whitespace/control characters) with an apostrophe. Fixtures include =1+1, +SUM(A1:A2), -10+20, @command, leading spaces/tab + formula, Unicode names, quotes, commas and embedded newlines. Numbers supplied as numbers remain numbers.

Installed Microsoft Excel opened the synthetic CSV read-only through normal Workbooks.Open: 9 rows, 1 column, no formula cells, Unicode preserved, embedded quotes/comma/newline preserved. An exploratory forced Workbooks.OpenText import split the embedded newline; normal CSV opening passed. Intended import settings must be specified to users; not every spreadsheet importer is certified. No real patient export was created. Evidence: scripts/phase4-synthetic-export.csv and phase4-spreadsheet-results.json.

**NOT VERIFIED:** hosted report RPC ownership/schema cache, real browser export/download click over live records, LibreOffice (not installed), every supported spreadsheet locale/import wizard and large production volume. Excel verification does not authorize storing/exporting real patient records.''')
section('N. Realtime Verification','''**CONFIRMED mocked/source:** advertised staff Realtime is implemented in staffAuth/useAppointmentRealtime, feeding Phase 2 invalidation with one admin appointment channel and burst debounce. Mounted Phase 3 tests assert role/unmount cleanup, timer cleanup, no duplicate channel/refresh storm and no patient subscription. Same-client mutation refresh works independently of Realtime and is tested by actual mounted Booking handlers.

enable_phase3_realtime.sql only adds appointments to an existing supabase_realtime publication if absent, keeps DEFAULT replica identity and does not broaden RLS. **NOT VERIFIED:** actual two-admin-browser event transport, reconnect, hosted RLS filtering/replication configuration and patient event isolation. Browser harness deliberately disables remote WebSockets, so its two SDK sessions provide no live Realtime evidence. Optional publication installation is required before claiming advertised cross-client updates; patient remote updates remain intentionally absent.''')
section('O. Browser / Routing Verification',table(['Browser check','Chrome','Edge'],[(name,'PASS','PASS') for name in dict.fromkeys(x['name'] for x in browser['checks'])])+'''
Isolated headless Chrome and Edge used new temporary profiles, actual dist assets/React/Supabase SDK, loopback static SPA hosting and 390×844 mobile viewport. All non-loopback HTTP requests were fulfilled/blocked; WebSockets were redirected offline. No personal browser cookies/storage were used. Mobile patient booking fits the viewport and screenshots are saved as scripts/phase4-chrome-mobile.png and phase4-edge-mobile.png. Browser functional checks are a mocked transport boundary, not real Supabase E2E or a complete visual review of every staff form.

Both saved mobile screenshots were visually inspected: heading, booking steps, doctor card, View Profile and Select Doctor controls are legible and fit the viewport; no blocker was observed on that screen. This does not certify uninspected staff dialogs, every responsive page, or assistive-technology behavior.

src/App.tsx actual routes: / → /patient/login; /patient/login provides login and registration mode (no separate registration URL); /patient/dashboard, /patient/book, /patient/appointments, /patient/history, /patient/profile, /patient/settings; /appointments/login, /appointments/dashboard, /appointments/booking, /appointments/check-in, /appointments/patients, /appointments/doctors, /appointments/reports, /appointments/settings. Section index redirects dashboard; outer wildcard and /queue-board/* redirect patient login. All named direct URLs reload through the synthetic static SPA fallback and restore SDK session. Actual deployment must configure equivalent history fallback.

Anonymous protected URLs go to the appropriate login. Patient storage alone does not open staff; injected patient-role staff/admin-role patient sessions fail closed. Invalid /patient/not-a-route renders blank because nested Routes has no wildcard; outer /not-a-route redirects login. Retained LOW limitation, not operational authorization bypass. Dedicated 404/error-boundary UX remains absent. Native date/dropdown/dialog/form behavior is exercised in the patient flow; the full staff mutation/responsive matrix is NOT VERIFIED.''')
section('P. Secret / Demo Account Hygiene','''git ls-files .env returns no entry: **untracked**. git ls-files secret.txt returns its filename: **tracked**. Contents were privately scanned without outputting values. JWT-like material is present and the parsed role category is **anon**; password/service-role-token category was not detected. This is not proof of a privileged service-role credential leak: an anon public key is normally frontend material and still depends on RLS. Current validity/signature, any non-JWT credential format, old history and deployed key permissions were not independently verified.

Required private hygiene review: remove unnecessary credential files from tracking through a separately reviewed change, inspect history privately, rotate any exposed nonpublic credentials if discovered, and review history cleanup if appropriate. Do not indiscriminately rotate a project signing secret based solely on an anon-role claim, and do not rewrite history automatically. No file/credential rotation was performed in this verification phase.

Demo account/password definitions remain in the local seed.cjs; no passwords are reproduced here. The script refuses non-loopback targets; README/setup explicitly require removing/rotating deployed demonstration identities. full.sql contains demo data. No hosted account inventory or seeder was run. Isolated school/demo synthetic identities are acceptable; real production must prove known default accounts are absent or rotated. Existing admin legitimacy must be reviewed because past escalation cannot be inferred/repaired by a preserving migration.

.env.example contains fake frontend values and server secret names only. Browser request metadata was classified without printing keys; see frontendCredentialRoleCategories in phase4-browser-results.json. That local claim classification is not a hosted credential audit. Secrets belong only in Edge secret manager/Vault; service-role must never enter VITE_* or frontend code.''')
trace=[
('E1 patient self-promotion','CRITICAL','1','FIXED','Column ACL/default role/admin RPC; Phase 1/4 attacks'),('E2 unrestricted appointment writes','CRITICAL','1','FIXED','SELECT-only browsers; authorized RPCs; Phase 1/4'),('E3 patient picker advertises other occupied slots','HIGH','2','FIXED','Privacy-safe common availability; Phase 2/4'),('E4 seconds/fractions and overlapping schedule slots','HIGH','2','FIXED','Minute/grid CHECK/validator + schedule exclusion; exact-start interval limitation separate'),('E5 duplicate/overlap/zero duration schedules','HIGH','2','FIXED','CHECK/GiST exclusion; safe incompatible rollback'),('E6 truthy/restored wrong role guard','HIGH','1–2','FIXED','Exact role; mounted and Chrome/Edge wrong-role cases'),('E7 auth stale identity/races','HIGH','2–3','FIXED','Generation/atomic packet/deadlines/listener cleanup'),('E8 name linking/ignored linkage failure','HIGH','2–3','FIXED','Exact UUID provisioning/link RPC; explicit failures'),('E9 reschedule fallback new booking/false success','HIGH','1','FIXED','Fail closed RPC-only; rollback/ownership'),('E10 edited reschedule reason ignored','MEDIUM','3','FIXED','Reason explicitly read-only for reschedule; authoritative original retained'),('E11 staff upcoming list stale','MEDIUM','2','FIXED','Shared mutation invalidation; actual mounted handlers'),('E12 check-in date/status/timestamp/pending','HIGH','1–3','FIXED','Backend clinic-day/state/timestamp; pending handled'),('E13 browser/server clinic timezone','HIGH','2–3','FIXED','Shared Manila utilities, SQL and browser timezone tests'),('E14 reports names/dates/truncation','MEDIUM','3','FIXED','Admin SQL ID aggregates/paging; 1,505 fixture total'),('E15 notification CORS','HIGH','3','FIXED','Real handler OPTIONS/exact origin; offline tests'),('E16 provider failure falsely successful','HIGH','3','FIXED','Structured accepted/stubbed/error/delivery and ledger'),('E17 null/malformed notification payload','MEDIUM','3','FIXED','Bounded body/UUID/type/auth validation'),('E18 status/reschedule/cancel races','HIGH','1–2','FIXED','Locks/transactional allowed transitions'),('E19 missing validation/repeated submit','MEDIUM','1–3','FIXED','Backend form triggers/constraints + sync mutation gate'),('E20 policy drop/rerun migration defect','MEDIUM','1','FIXED','Transactional canonical security copies; repeat full chain'),('E21 Leave from unrelated week','MEDIUM','2','FIXED','Exact displayed clinic-week dates regression'),
('Tracked secret.txt','HIGH','Review 4','NOT VERIFIED','Tracked anon-role JWT found; privileged leak not confirmed; validity/history review outstanding'),('Embedded demo/default credentials','HIGH if deployed','3 partial','NOT VERIFIED','Loopback guard/docs fixed; actual deployed accounts unknown'),('Insufficient SECURITY DEFINER hardening','MEDIUM','1–3','FIXED','Safe search_path/qualified tables/explicit EXECUTE; actual hosted owners unknown'),('Notification stub PII/body logs','HIGH','3','FIXED','Minimal metadata/no sensitive payload/provider logs'),('CSV formula injection','MEDIUM','3','FIXED','Shared encoding + malicious fixtures + actual Excel normal open'),('Overbroad table grants','MEDIUM','1–3','FIXED','Role/appointment/linkage column and worker ACLs; hosted drift unknown'),
('F missing auth-column protection/staff validation/state machine','Not separately rated','1','FIXED','Protected role/staff RPC/lifecycle'),('F missing privacy-preserving availability','Not separately rated','2','FIXED','Slot/date RPC only safe data'),('F reminder installed executable job','Not separately rated','3 definition','NOT VERIFIED','Deployable Vault cron exists; no live job installed/verified'),('F notification ledger/retries/idempotency','Not separately rated','3','FIXED','Versioned outbox/claim/finish/callback tests'),('F frontend Realtime missing','Not separately rated','3 code','NOT VERIFIED','Subscription code/mocks pass; actual publication/transport unknown'),('F doctor name/specialty editing missing','Not separately rated','3','FIXED','Validated non-destructive doctor edit UI/backend'),('F patient archive/delete','Not separately rated','None','ACCEPTED LIMITATION','No requirement/specification justified destructive CRUD; history preserved'),('F intentional clinic/Auth linkage absent','Not separately rated','2–3','FIXED','Admin exact UUID link/form/conflict refusal'),('F automated behavioral/concurrency tests absent','Not separately rated','1–4','FIXED','Runnable safe SQL/hooks/browser suites'),('Email/Resend, PDF/Excel export/print, clinic-wide closure','Not required','None','ACCEPTED LIMITATION','SMS/CSV/doctor-specific blocking only; no unsupported claims'),('Self-service password recovery','Not required','3 truthful UX','ACCEPTED LIMITATION','Explicit clinic-assisted help; no reset-email workflow'),
('H Auth user can lack profile/patient','Not separately rated','2','FIXED','Provisioning RPC/explicit failure; real Auth trigger not assumed'),('H unlinked patients and Auth deletion SET NULL','Not separately rated','2 preserved','ACCEPTED LIMITATION','Intentional clinic records/history; verified exact links only'),('H missing schedule/appointment grid constraints','Not separately rated','2','FIXED','Minute grid/duration/overlap; catalog and rejected fixtures'),('H blocked date can conflict with active visit','Not separately rated','2','FIXED','New conflicting block refused; historical conflicts preserved for review'),('H nullable doctor flags','Not separately rated','None','ACCEPTED LIMITATION','NULL not treated as active; no unrelated history rewrite'),('H recurrence ownership/cycle integrity','Not separately rated','1 partial','ACCEPTED LIMITATION','Authorized follow-up parent validation; trusted backend remains privileged'),('H visit note patient/appointment mismatch','Not separately rated','3','FIXED','Form trigger matches linked appointment/patient and creator'),('H empty/whitespace/oversized text','Not separately rated','3','FIXED','Backend validators/preflight plus frontend errors'),('H audit only appointment inserts/updates','Not separately rated','Preserved','ACCEPTED LIMITATION','No full demographic/delete audit added; browser appointment deletes denied'),('H IF NOT EXISTS cannot validate arbitrary live schema','Not separately rated','1–3 preflight','NOT VERIFIED','Critical index/rows checked locally; real drift requires review'),('H legacy queue columns retained','Not separately rated','1 documented','ACCEPTED LIMITATION','Modern fresh schema clean; matching legacy history retained intentionally'),('History inactive doctor join missing','Not separately rated','3','FIXED','Patient can read own historical inactive doctor'),
('O missing dependencies/build could not run','Tooling','1–4','FIXED','Clean npm ci and final TypeScript/Vite pass'),('O Edge code not in tsconfig scope','Not separately rated','3','FIXED','Seven-file offline Edge type verification; actual Deno runtime unknown'),('O Save User decorative checkbox','LOW','3','FIXED','Removed; truthful persistent-session wording'),('O notification setting display-only','Not separately rated','3 documented','ACCEPTED LIMITATION','Deployment flag display, not editable provider configuration'),('O independent room save absent','Not separately rated','Preserved','ACCEPTED LIMITATION','Room persisted with authorized clinical transition'),('O visit-note read interface absent','Not separately rated','Preserved','ACCEPTED LIMITATION','Safe creation exists; reading interface deferred'),('O errors treated as empty/no mutation result/try-finally','Not separately rated','2–3','FIXED','QueryState/error/retry/returned rows/useMutation tests'),('O profile display-name context stale','Not separately rated','3','FIXED','Atomic patient/profile save + identity refresh'),('O staff-specific password hint in patient login','LOW','3','FIXED','Shared explicit clinic/admin-assisted wording'),('O obsolete semicolon/setup instructions and .env.example missing','LOW','3','FIXED','Fake template and current npm/setup instructions'),('O nested 404/application error boundary absent','LOW','None','ACCEPTED LIMITATION','Blank invalid nested route confirmed; external fallback remains'),('O hardcoded/mock frontend clinical/report data','No confirmed defect','Audit','ACCEPTED LIMITATION','No fake production data found; Phase 4 fixtures isolated in scripts'),('O optional live verification mutates hosted data','HIGH operational','1','FIXED','verify.mjs static; no environment connection/write branch'),('O broad table/REST fetching and report caps','MEDIUM/volume','3 partial','ACCEPTED LIMITATION','Reports/history complete; some intentional bounded lookups remain'),('O schedule/patient-time/audit/trigram index suggestions','Performance','2 partial','ACCEPTED LIMITATION','Schedule GiST/indexes present; other changes require volume evidence'),('O duplicate auth reads/stale filter response','Not separately rated','2','FIXED','IdentityCoordinator/RequestGeneration/abort tests'),('O repeated schedule/block reload and mutable multi-page snapshots','LOW','Preserved','ACCEPTED LIMITATION','Correctness maintained; not transactionally frozen browser pagination'),('O nonexistent frontend confirmed status','MEDIUM','3','FIXED','Removed as API/status value; display wording only'),
('P1 existing historically compromised admin assignments','HIGH operational','Pending','NOT VERIFIED','Preserving migrations cannot judge legitimacy; private audit needed'),('P1 trusted backend/service-role/unknown RPC rights','HIGH operational','Boundary preserved','NOT VERIFIED','Local browser ACLs pass; hosted owner/membership/RPC drift unknown'),('P2 real extension/owner/auth.users lock compatibility','HIGH operational','Pending staging','NOT VERIFIED','Plain PostgreSQL 18 shim passes; platform setup unknown'),('P2 real bad schedules/non-minute/blocked historical visits','HIGH operational','Safe rejection','NOT VERIFIED','Fixture rollback confirmed; actual real rows not inspected'),('P2 schedule grid changes can overlap old interval starts','MEDIUM','Not changed','ACCEPTED LIMITATION','Only exact-start uniqueness promised; operator reconciliation needed'),('P2 long-open dashboard midnight/week rollover','LOW','Not changed','ACCEPTED LIMITATION','Shared timezone correct; refresh at rollover required'),('P2 duplicate account/history-link conflicts','MEDIUM','2–3 controlled','ACCEPTED LIMITATION','Refusal correct; no automatic merge/delete'),('P3 simultaneous demographic duplicates','MEDIUM','3 partial','ACCEPTED LIMITATION','Draft UUID/review warning, not demographic global uniqueness'),('P3 ambiguous sends/expired leases/stubs/in-flight changes','MEDIUM','3 conservative','ACCEPTED LIMITATION','Manual reconciliation; no unconditional retries/retraction'),('P3 callback retry/public URL/throughput/quota/consent','HIGH/MEDIUM operational','Pending staging','NOT VERIFIED','Mock signatures/queue tests only'),('P3 hosted Auth/password/email-confirmation policy','HIGH operational','Pending staging','NOT VERIFIED','Local config does not configure hosted policy'),('P3 spreadsheet rendering/file exports','MEDIUM','4 partial','NOT VERIFIED','Normal Excel synthetic open passes; live export/other importers unknown'),('P3 hosted scheduler/publication/function deployment','HIGH operational','Pending staging','NOT VERIFIED','Only repository definitions/local mocks'),('P3 live two-client Realtime/reconnect/privacy','MEDIUM','Pending staging','NOT VERIFIED','Mounted cleanup/isolation only; no remote subscription'),('P3 demonstration seeder generation','Operational','Not run','NOT VERIFIED','Target refusal tested; no hosted/local accounts seeded'),('P3 Vite large bundle warning','LOW','Deferred','ACCEPTED LIMITATION','Build warning remains; no feature/performance redesign'),('New dependency security advisories','HIGH/MODERATE','4 review','STILL BROKEN','npm audit exit 1; vulnerable versions retained, exposure prerequisites documented')]
section('Q. Original Audit Finding Traceability',table(['Original Finding','Original Severity','Phase Fixed','Current Status','Evidence'],trace)+'''
FIXED denotes tested current workspace source/local SQL; actual hosted installation is separately NOT VERIFIED. Every numbered E1–E21, security finding, missing-capability group, database/UI/performance finding and prior-report unresolved category is represented, including intentional unsupported features. No original finding is silently treated as a deployed fix.''')
section('R. Remaining Known Limitations','''**HIGH / release prerequisites:** actual staging Auth/PostgREST/JWT/RLS/RPC ownership/schema cache; real-data migration preflight/backups/restore rehearsal; historical admin legitimacy; private tracked-material/history and deployed demo-account review; dependency security resolution or formally bounded applicability acceptance; correct function secrets/origins/gateway; real notification provider/callback/scheduler verification if advertised operational.

**MEDIUM / operational limitations:** exact-start protection does not prevent old-grid duration overlaps; identity histories are not automatically merged; demographic duplicates require review; uncertain/stubbed/in-flight messages require reconciliation; five-message worker capacity unmeasured; real Realtime isolation/reconnect unknown; full staff browser mutations/live password changes and expired Auth sessions remain unverified; exported data needs authorized storage/import procedures.

**LOW / accepted:** old SQL header demonstration/setup hints are subordinate to the explicit current README/setup and deployment inventory (never use demo full.sql/seed.cjs for hosted upgrades); >500 kB bundle warning; blank invalid nested route/no application error boundary; long-open midnight rollover refresh; some bounded lookups/list snapshots/performance suggestions; note-reading/independent room-save absent; no invented email/PDF/Excel export/print/destructive archive features.

Dependency audit exact snapshot: four packages, three moderate/one high, zero critical. Vite 5.4.21/esbuild 0.21.5 include development-server disclosure/path issues. The high Windows filesystem-deny bypass requires exposed development-server conditions; static dist serving does not run that server. Keep development loopback-only and never deploy Vite dev/preview as a public clinical server. The maintainer lists patched Vite branches including 6.4.3; any toolchain upgrade must be deliberate and rerun all tests. [Vite upstream advisory](https://github.com/vitejs/vite/security/advisories/GHSA-fx2h-pf6j-xcff).

React Router 6.30.6 is flagged for untrusted navigation redirects and SSR constructor injection. Source uses hardcoded internal navigation/declarative BrowserRouter, with no SSR hydration. SSR advisory explicitly excludes Declarative Mode; redirect applicability is an inference from current fixed-target calls, not a vulnerability remediation. Reassess if untrusted navigation/SSR is added. The lockfile remains flagged; do not claim clean dependency security. [Redirect upstream advisory](https://github.com/remix-run/react-router/security/advisories/GHSA-wrjc-x8rr-h8h6), [SSR upstream advisory](https://github.com/remix-run/react-router/security/advisories/GHSA-337j-9hxr-rhxg).

Full sanitized package/advisory/fix metadata: scripts/phase4-dependency-audit.json. npm audit --json exited 1; its diagnostic wrapper succeeded in saving that result. No npm audit fix --force or major Router/toolchain migration was performed during feature freeze.''')
section('S. Exact Deployment Order','''The following is a reviewed inventory/order, **not deployment performed**.

''' + table(['Order','Classification','File/action','Conditions'],[
('0','REQUIRED','Backup, private catalog/data/admin/key/demo review; isolated staging','Matching modern schema/owner/extensions; compatible fixtures; no resets'),('1','REQUIRED existing modern DB','supabase/fix_phase1_security.sql','Preserve transaction; role/appointment ACLs/RPCs; unchanged index'),('2','REQUIRED existing modern DB','supabase/fix_phase2_booking_availability.sql','After Phase 1; stop on invalid schedule/timestamp preflight'),('3','REQUIRED existing modern DB','supabase/fix_phase3_notifications_reports.sql','After Phase 2; stop on invalid demographics/notes preflight'),('4','REQUIRED for connected notifications','supabase/config.toml and functions/send-confirmation, send-reminders, notification-status','Stage secrets/exact origins; handler authentication retained; shared modules included'),('5','REQUIRED when claiming automation; otherwise OPTIONAL','supabase/fix_phase3_scheduler.sql','After SQL/functions; Vault/pg_cron/pg_net and three named secrets; verify live unique job'),('6','OPTIONAL installation; REQUIRED for advertised cross-client updates','supabase/enable_phase3_realtime.sql','Existing publication; verify RLS/two synthetic admin clients/reconnect'),('7','REQUIRED frontend release','npm ci → npm run build → serve dist on proper static HTTPS host','Correct PUBLIC config; SPA history fallback; notifications enabled only after verified backend'),('8','REQUIRED release gate','supabase/rls_tests.sql read-only catalog review + synthetic staging E2E','Actual REST attacks/concurrency/provider/scheduler/report evidence'),('Separate path','FRESH ONLY; DO NOT USE FOR EXISTING DB','supabase/schema.sql','Full non-demo fresh definitions already include Phase 1–3; bootstrap admin privately'),('Separate legacy path','CONDITIONAL; DO NOT USE blindly on modern DB','supabase/migrate_patient_booking.sql','Only matching reviewed pre-cleanup legacy installation; retains historical legacy behavior'),('Never upgrade/production','DO NOT USE FOR EXISTING DATABASE','supabase/full.sql','Schema-plus-demo convenience, local disposable only'),('Never hosted/upgrade','DO NOT USE FOR EXISTING DATABASE','supabase/seed.cjs','Local-only demonstration accounts/data; do not bypass guard with tunnel'),('Reference only','DO NOT USE AS executable scheduler','supabase/cron.sql','Pointer/documentation, use reviewed Phase 3 scheduler')])+'''
Server variables: SUPABASE_URL, SUPABASE_ANON_KEY, SUPABASE_SERVICE_ROLE_KEY, CRON_SECRET, NOTIFY_ALLOWED_ORIGINS, TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_FROM_NUMBER; optional NOTIFY_STATUS_CALLBACK_URL. Vault names: medicappointment_url, medicappointment_anon_key, medicappointment_cron_secret. No values belong in frontend/reports/Git. Frontend variables: VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY and optional VITE_NOTIFY_ENABLED.

Refresh PostgREST schema cache through the authorized operational procedure after staged RPC changes if needed. Verify all existing function owners/grants and first-admin bootstrap. Coordinate source/frontend with migrations; old direct-write clients are deliberately rejected. Hosted function/scheduler/publication/frontend deployment needs separate authorization; none occurred here.''')
section('T. School Demonstration Readiness','''**NOT READY for the requested complete connected demonstration.** Safe local SQL test demonstrations, code walkthroughs and actual-browser synthetic transport exercises are successful. They can demonstrate implementation evidence, but must be labelled as synthetic/mocked and cannot establish live registration, persisted clinic flows or automation.

Before raising to READY WITH KNOWN LIMITATIONS: configure a disposable local Supabase-compatible full stack or explicitly authorized isolated staging with synthetic Auth identities; install reviewed schema/migrations; bootstrap admin safely; rehearse complete patient and staff flows through actual Auth/PostgREST; verify direct refresh; establish provider-stub messaging and openly identify scheduler/Realtime limitations. Never use real patient data or seed a hosted database with the local seeder. A notification-disabled/manual-refresh demonstration may be acceptable only if those limitations are explicitly declared.''')
section('U. Staging Readiness','''**READY WITH PREREQUISITES.** The candidate builds, local fresh and compatible incremental SQL installations pass, and security/lifecycle regressions are preserved. No confirmed new application blocker prevents a deliberate isolated staging trial.

Prerequisites: authorized isolated project/local complete stack; compatible owner/extensions/Auth policies/RPC schema cache; backups and real preflight review if upgrading; appropriate exact origins/server secrets/Vault; synthetic accounts and destinations created through deliberate Auth/admin operations; dependency/hygiene review; full real HTTP RLS/role attack and UI rehearsal. Claiming reminders or Realtime additionally requires installed live job/publication and observed outcomes. This classification authorizes no automatic deployment.''')
section('V. Production Readiness','''**NOT READY.** Local tests cannot establish deployed RLS, Auth, privacy, backups, existing data validity, historical role legitimacy, live messaging/scheduler/Realtime, or patient-operational readiness. The flagged dependency tree and repository/demo hygiene need a documented disposition.

Production requires all staging gates, actual protected credential/account review, migration rollback/restore plans and ownership/ACL checks, synthetic adversarial REST and concurrency evidence, real-browser patient/staff flows, truthful notification consent/destination/quota/unknown-send operations, signed callback/cron verification where enabled, secure static hosting/HTTPS/history fallback, monitoring/support responsibility and approved historical schedule/link reconciliation rules. No real patient information was used to shortcut those checks.''')
section('W. Final Go/No-Go Conditions','''**GO:** continue a separately authorized isolated staging verification with the exact inventory in S; preserve Phase 1–3 and feature freeze. Local regression and synthetic browser/Excel evidence are confirmed.

**NO-GO:** production rollout now; a complete connected school demonstration without a real synthetic-backend rehearsal; treating a source scheduler/subscription as installed automation; running full.sql/seed.cjs on hosted services; bypassing preflight failures by deleting/rounding history; exposing Vite development tools or server secrets; automatically replaying unknown external sends.

Final checks: final regression run passed all ten commands; 78 frozen source/configuration/SQL/package hashes remain unchanged; this report contains A–W; checklist/continuation were updated; original reports preserved. Workspace Vite restoration and final file metadata are recorded in PHASE4_CONTINUATION.md. No production deployment, database reset or Phase 5 was started. **Phase 4 stops here.**''')
path=root/'MEDICAPPOINTMENT_FINAL_VERIFICATION_REPORT.md'
path.write_text('\n\n'.join(out)+'\n',encoding='utf-8',newline='\n')
text=path.read_text(encoding='utf-8')
assert all('\n## '+chr(c)+'. ' in text for c in range(ord('A'),ord('W')+1))
print(json.dumps({'path':str(path),'bytes':path.stat().st_size,'lines':len(text.splitlines()),'sectionsAThroughW':True,'frozenFilesUnchanged':len(baseline)}))
